---

- name: Make and make install and reload NGINX
  hosts: legacy_puzzle_massive
  user: dev
  become: true
  tasks:


    - name: "Make"
      shell: "source bin/activate && make ENVIRONMENT=production"
      args:
        executable: /usr/bin/bash
        chdir: /usr/local/src/puzzle-massive/
    - name: "Make install"
      shell: "source bin/activate && make install ENVIRONMENT=production"
      args:
        executable: /usr/bin/bash
        chdir: /usr/local/src/puzzle-massive/
    - name: "NGINX configuration test"
      command: "nginx -t"
    - name: Reload NGINX
      ansible.builtin.systemd:
        state: reloaded
        daemon_reload: yes
        name: nginx
